name: Update Word Cloud Data

on: 
 push:
    branches: [main]
    paths:
      - 'pages/publications.md'        # 只有 pages 目录下的文件变更才触发
    paths-ignore:
      - 'assets/js/wordcloud_data.js'  # 忽略这个文件的变更
 workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
    - name: Run
      run: |
        python3 generate_wordcloud.py
        git config --local user.name "${GITHUB_ACTOR}"
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git add asset.js
        git commit -m "Updated Word Cloud Data"
        git push "${remote_repo}" HEAD:google-scholar-stats --force